server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moocoder?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: username
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
  security:
    user:
      name: name
      password: password
  mail:
    host: smtp.example.com
    username: moocoder@example.com
    password: password

moocoder:
  secret: RandomSecret
  gitlab:
    host: http://repo.moocoder.example.com
    git-proxy: http://moocoder.example.com
    username: username
    token: token
  jenkins:
    host: http://ci.moocoder.example.com
    username: username
    token: token
  mail:
    from: moocoder@example.com
  storage:
    type: local
    properties:
      location: ./problem